services:
  chumpkin:
    # Make sure to change the tag to the chumpkin version you want to use.
    # https://github.com/callenflynn/Chumpkin/pkgs/container/chumpkin/versions?filters%5Bversion_type%5D=tagged
    #image: ghcr.io/callenflynn/chumpkin:master
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./data:/chumpkin
      # Use the following, if you want to make your config immutable
      #- ./config:/pumpkin/config:ro
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    read_only: true
